version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - model-data:/root/.u2net  # Persistir el modelo descargado
    environment:
      - PYTHONUNBUFFERED=1  # Mejor logging

volumes:
  model-data:  # Volumen para el modelo